services:
  datanode-worker:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode_worker
    network_mode: "host"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://192.168.56.11:8020
      - HDFS_CONF_dfs_datanode_hostname=worker-vm-2
      - HDFS_CONF_dfs_datanode_use_datanode_hostname=true
      - HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check=false
    volumes:
      - hadoop_worker_data:/hadoop/dfs/data
    restart: always

  spark-worker-remote:
    image: apache/spark:3.5.1
    container_name: spark_worker_remote
    network_mode: "host"
    environment:
      - SPARK_MASTER=spark://192.168.56.11:7077
      - SPARK_LOCAL_IP=192.168.56.12
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://192.168.56.11:7077
    restart: always

# BURASI ÇOK ÖNEMLİ: Aşağıdaki tanım yukarıdakiyle birebir aynı olmalı
volumes:
  hadoop_worker_data:
